//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calculator
    {
        public int CalculatorId { get; set; }
        public string CalculatorName { get; set; }
        public string Model { get; set; }
        public int SellerId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string imagePath { get; set; }
        public string Price { get; set; }
        public Nullable<int> BuyerId { get; set; }
    }
}
